runtime: nodejs12
env: standard
instance_class: F1
handlers:
  - url: /
  static_files: client/public/index.html
  upload: www/index.html
  - url: /(.*)
    static_files: client/public/\1
    upload: www/(.*)
